[project]
name = "queries-are-not-alone"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "datasets>=4.4.1",
    "faiss-cpu>=1.13.1",
    "openai-clip>=1.0",
    "torchcodec>=0.8.1",
    "tqdm>=4.67.1",
]

[build-system]
requires = ["setuptools>=69", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = ["utils", "model", "scripts", "config"]
exclude = ["assets", "checkpoints", "data"]
