joint_dataset_path = "assets/datasets/msrvtt_joint_preprocessed"

batch_size = 32
num_epochs = 10
lr = 1e-4
weight_decay = 1e-4
device = "cuda"
num_workers = 4
grad_clip = 1.0

# model/loss settings
hidden_dim = 512
temperature_init = 0.07
sweeper_label_smoothing = 0.0
sweeper_num_segments = 4

# CLIP backbone
clip_model_name = "ViT-B/16"
